# numpy tutorial

In [1]:
import numpy as np


In [2]:
a=np.array([[1,2,3,4,5]], np.int64)

In [3]:
a

array([[1, 2, 3, 4, 5]], dtype=int64)

# accessing array

In [4]:
a[0,1]


2

In [5]:
a.shape

(1, 5)

In [6]:
a.dtype

dtype('int64')

In [7]:
a[0,1]=100

In [8]:
a

array([[  1, 100,   3,   4,   5]], dtype=int64)

# array creation:convergion from other python strucher

In [9]:
b=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]], np.int64)

In [10]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int64)

In [11]:
b.shape

(4, 4)

In [12]:
b.dtype

dtype('int64')

In [13]:
b.size

16

In [14]:
zeros=np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
renge=np.arange(16)

In [17]:
renge

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
lenspace=np.linspace(1,4,4)

In [19]:
lenspace

array([1., 2., 3., 4.])

In [20]:
emp=np.empty((4,5))

In [21]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.60219442e-306, 7.56587584e-307],
       [7.56593017e-307, 1.24610383e-306, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306],
       [2.22522597e-306, 1.33511969e-306, 1.78022342e-306,
        1.05700345e-307, 1.11261027e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        6.23059726e-307, 1.42419530e-306]])

In [22]:
emplike=np.empty_like(lenspace)

In [23]:
emplike

array([1., 2., 3., 4.])

In [24]:
ide= np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr=np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr=arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr=arr.ravel()

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.shape

(99,)

# access kudun kuthe aahe te

In [34]:
x=([1,2,3],[4,5,6],[7,1,0])

In [35]:
ar=np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar.sum(axis=0)

array([12,  8,  9])

In [38]:
ar.sum(axis=1)

array([ 6, 15,  8])

***row cha colum colum cha row

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

***flat mhanje print kart saglya la

In [40]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


***number of deimenshal

In [41]:
ar.ndim

2

In [42]:
ar.nbytes

36

***creating one demational arry

In [43]:
a=np.array([1,3,4,56,2])

In [44]:
a.argmax()

3

In [45]:
a.argmin()

0

In [46]:
a.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.argmax()

6

In [49]:
ar.argmin()

8

In [50]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [51]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [52]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [53]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [54]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

***two matrix la apn addition subtrastion division multiplication karu shakto seee

In [56]:
ar2=np.array([[1, 5, 4],[4, 5, 7],[8, 3, 1]])

In [57]:
ar2

array([[1, 5, 4],
       [4, 5, 7],
       [8, 3, 1]])

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
ar+ar2

array([[ 2,  7,  7],
       [ 8, 10, 13],
       [15,  4,  1]])

In [60]:
ar*ar2

array([[ 1, 10, 12],
       [16, 25, 42],
       [56,  3,  0]])

In [61]:
ar/ar2

array([[1.        , 0.4       , 0.75      ],
       [1.        , 1.        , 0.85714286],
       [0.875     , 0.33333333, 0.        ]])

*** suare root kadych asel tr

In [62]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

***find kary kute motha elementt aahe

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))